### ISSUE TITLE
Compatibility with Xubuntu 16.04

### ISSUE THREAD

**Issue by yaztromo99** [shimmerproject/Bluebird#13]
HI,
Have been using bluebird theme for some years, and was sad to see it go in 16.04. Apparently this is because bluebird does not support newer GTK3 versions.

Would it be trivial to provide compatibility so the theme can be used again in 16.04?

Thanks.

**Comment by jbicha** [comment]
(Xubuntu 16.04 LTS uses GNOME 3.18)

**Comment by rahilwazir** [comment]
Here is the latest build: https://bugs.launchpad.net/~shimmerproject/+archive/ubuntu/daily/+build/9754529

```
$ sudo add-apt-repository ppa:shimmerproject/daily
$ sudo apt update
$ sudo apt install bluebird-gtk-theme
```

**Comment by dinsdalepiranha** [comment]
As the EOL of Xubuntu 14.04 is the same as 16.04 and I see nothing compelling in the 16.04 release notes (other than the removal of Bluebird, my preferred GTK+ theme) I think the choice is clear.

Sticking with 14.04 until this is resolved.

**Comment by yaztromo99** [comment]
@rahilwazir Thanks for the point to the repo. It's working for me on 15.10, even though bluebird is included on this release it's got some issues but the repo version fixed them. Will try on 16.04 soon, but assuming it will be fine.

**Comment by ddelabru** [comment]
I am about to make a new release of Bluebird tonight that includes a new gtk3 theme based on the latest version of Greybird, which should provide better support for recent GTK3 versions.
