### ISSUE TITLE
Broken with GTK 3.20

### ISSUE THREAD

**Issue by jbicha** [shimmerproject/Bluebird#16]
GTK 3.20 includes a major rewrite of the theming code and broke all existing GTK3 themes.

Since Bluebird is generally unmaintained these days, we need a volunteer to update Bluebird to provide at least minimal GTK 3.20 support. Some people do use Bluebird still. (It's packaged in quite a few Linux distros).

**Comment by hroncok** [comment]
Just updated from Fedora 23 to 25 and Bluebird is still there but all GTK3 stuff is broken.

![bluebird](https://cloud.githubusercontent.com/assets/2401856/20563096/4e946ff0-b187-11e6-930a-499ad734c323.png)

As one of the bluebird package maintainers in Fedora I now face the decision whether to drop the package form Fedora or not. I don't have knowledge need for fixing this.

**Comment by hate-m-dollarsign** [comment]
Fixed by #20. Please close.

**Comment by ddelabru** [comment]
@hate-m-dollarsign: thanks about to close this issue

**Comment by ddelabru** [comment]
@hroncok: I'm just going through the issue queue tonight to see what can be closed, and then I think I'm going to make a release that incorporates the new gtk3 theme. I'll ping you when I do.

**Comment by ddelabru** [comment]
@hroncok: I just tagged release v1.3; I'd love to have it available from Fedora repos.
