### ISSUE TITLE
the checkbox dosn't work with gnome 3.14

### ISSUE THREAD

**Issue by ghost** [shimmerproject/Bluebird#5]
For exemple with psensor, synaptic, nemo... (debian jessie)

The new syntaxe of:
background-image: url("assets/exemple.png");
is:
-gtk-icon-source: -gtk-scaled(url("assets/exemple.png"));

i change my gtk-widgets-assets.css, but don't work, only case works, not the 
check!

bluebird original:
![capture blubird-original](https://cloud.githubusercontent.com/assets/9335916/4718219/d21bd854-591e-11e4-8d0a-d92a02cbeb21.png)
bluebird with change:
![capture blubird-modif](https://cloud.githubusercontent.com/assets/9335916/4718220/d2226aca-591e-11e4-84ce-cdcb956d619f.png)
exemple other theme works ok!
![capture other theme ok](https://cloud.githubusercontent.com/assets/9335916/4718218/d21a6410-591e-11e4-8c00-abca9f410ce0.png)

my new syntaxe for check and radio:

/*******************
- check and radio *
  ******************_/
  /_ draw regular check and radio items using our assets */
  .check,
  .check row:selected,
  .check row:selected:focus {
  -gtk-icon-source: -gtk-scaled(url("assets/checkbox-unchecked.png"));
  background-image: url("assets/checkbox-unchecked.png");
  }

.check:insensitive,
.check row:selected:insensitive,
.check row:selected:focus:insensitive {
    -gtk-icon-source: -gtk-scaled(url("assets/checkbox-insensitive.png"));
    background-image: url("assets/checkbox-unchecked-insensitive.png");
}

.check:active,
.check row:selected:active,
.check row:selected:focus:active {
    -gtk-icon-source: -gtk-scaled(url("assets/checkbox-checked.png"));
    background-image: url("assets/checkbox-checked.png");
}

.check:active:insensitive,
.check row:selected:active:insensitive,
.check row:selected:focus:active:insensitive {
    -gtk-icon-source: -gtk-scaled(url("assets/checkbox-checked-insensitive.png"));
    background-image: url("assets/checkbox-checked-insensitive.png");
}

.check:inconsistent,
.check row:selected:inconsistent,
.check row:selected:focus:inconsistent {
    -gtk-icon-source: -gtk-scaled(url("assets/checkbox-mixed.png"));
    background-image: url("assets/checkbox-mixed.png");
}

.check:inconsistent:insensitive,
.check row:selected:inconsistent:insensitive,
.check row:selected:focus:inconsistent:insensitive {
    -gtk-icon-source: -gtk-scaled(url("assets/checkbox-mixed-insensitive.png"));
    background-image: url("assets/checkbox-mixed-insensitive.png");
}

.radio,
.radio row:selected,
.radio row:selected:focus {
    -gtk-icon-source: -gtk-scaled(url("assets/radio-unselected.png"));
    background-image: url("assets/radio-unselected.png");
}

.radio:insensitive,
.radio row:selected:insensitive,
.radio row:selected:focus:insensitive {
    -gtk-icon-source: -gtk-scaled(url("assets/radio-unselected-insensitive.png"));
    background-image: url("assets/radio-unselected-insensitive.png");
}

.radio:active,
.radio row:selected:active,
.radio row:selected:focus:active {
    -gtk-icon-source: -gtk-scaled(url("assets/radio-selected.png"));
    background-image: url("assets/radio-selected.png");
}

.radio:active:insensitive,
.radio row:selected:active:insensitive,
.radio row:selected:focus:active:insensitive {
    -gtk-icon-source: -gtk-scaled(url("assets/radio-selected-insensitive.png"));
    background-image: url("assets/radio-selected-insensitive.png");
}

.radio:inconsistent,
.radio row:selected:inconsistent,
.radio row:selected:focus:inconsistent {
    -gtk-icon-source: -gtk-scaled(url("assets/radio-mixed.png"));
    background-image: url("assets/radio-mixed.png");
}

.radio:inconsistent:insensitive,
.radio row:selected:inconsistent:insensitive,
.radio row:selected:focus:inconsistent:insensitive {
    -gtk-icon-source: -gtk-scaled(url("assets/radio-mixed-insensitive.png"));
    background-image: url("assets/radio-mixed-insensitive.png");
}

.menuitem.check:active {
    -gtk-icon-source: -gtk-scaled(url("assets/menuitem-checkbox-checked.png"));
    background-image: url("assets/menuitem-checkbox-checked.png");
}

.menuitem.check:active:hover {
    -gtk-icon-source: -gtk-scaled(url("assets/menuitem-checkbox-checked-hover.png"));
    background-image: url("assets/menuitem-checkbox-checked-hover.png");
}

.menuitem.check:active:insensitive {
    -gtk-icon-source: -gtk-scaled(url("assets/menuitem-checkbox-checked-insensitive.png"));
    background-image: url("assets/menuitem-checkbox-checked-insensitive.png");
}

.menuitem.check:inconsistent:hover,
.menuitem.radio:inconsistent:hover {
    -gtk-icon-source: -gtk-scaled(url("assets/menuitem-checkbox-mixed-hover.png"));
    background-image: url("assets/menuitem-checkbox-mixed-hover.png");
}

.menuitem.check:inconsistent,
.menuitem.radio:inconsistent {
    -gtk-icon-source: -gtk-scaled(url("assets/menuitem-checkbox-mixed.png"));
    background-image: url("assets/menuitem-checkbox-mixed.png");
}

.menuitem.check:inconsistent:insensitive,
.menuitem.radio:inconsistent:insensitive {
    -gtk-icon-source: -gtk-scaled(url("assets/menuitem-checkbox-mixed-insensitive.png"));
    background-image: url("assets/menuitem-checkbox-mixed-insensitive.png");
}

.menuitem.radio:active {
    -gtk-icon-source: -gtk-scaled(url("assets/menuitem-radio-checkbox.png"));
    background-image: url("assets/menuitem-radio-checked.png");
}

.menuitem.radio:active:hover {
    -gtk-icon-source: -gtk-scaled(url("assets/menuitem-radio-checked-hover.png"));
    background-image: url("assets/menuitem-radio-checked-hover.png");
}

.menuitem.radio:active:insensitive {
    -gtk-icon-source: -gtk-scaled(url("assets/menuitem-radio-checked-insensitive.png"));
    background-image: url("assets/menuitem-radio-checked-insensitive.png");
}

GtkIconView.content-view.cell.check {
    -gtk-icon-source: -gtk-scaled(url("assets/grid-selection-unchecked.png"));
    background-image: url("assets/grid-selection-unchecked.png");
}

GtkIconView.content-view.cell.check:active {
    -gtk-icon-source: -gtk-scaled(url("assets/grid-selection-checked.png"));
    background-image: url("assets/grid-selection-checked.png");
}

**Comment by ddelabru** [comment]
The gtk3 theme has also been entirely replaced for an upcoming release, so the checkbox issue should no longer occur. Please open a new issue if a similar problem occurs after today's release.
